/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2018-10-16 05:19:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.io.*;
import java.sql.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 Connection con;
String url="jdbc:mysql://127.0.0.1:3306/gallery";
String id="gallery";
String pwd="eecs118";


 public void list_Gallery(JspWriter out) throws IOException{
    try{
        con= DriverManager.getConnection(url,id,pwd);
        Statement stmt = con.createStatement();
        String sql="SELECT * FROM gallery";
        ResultSet rs=stmt.executeQuery(sql);
        //prepare table and form FORM NAME : 
        out.println("<form NAME=\"gallerytable\" method=\"POST\">");
        out.println("<Table>");
        out.println("Table of Galleries");
        out.println("<tr>");
        out.println("<td> ID </td>" + "<td> Gallery Name </td>" + "<td> Description </td>");
        while (rs.next()) {
            out.println("<tr>");
            out.println("<td>"+rs.getString("gallery_id")+"</td>");
            out.println("<td>"+rs.getString("name")+"</td>");
            out.println("<td>"+rs.getString("description")+"</td>");
            out.println("<td> <input type=\"radio\" name=\"galleryselect\" value=\""+rs.getString("gallery_id")+"\" </td>");
            out.println("</tr>");
        }
        out.println("</Table>");
        out.println("<input type = \"submit\" value = \"View Gallery\"/>");
        out.println("</form>");
    }
    catch(SQLException ex){
        String message = "ERROR: " + ex.getMessage();
        out.println(message);
        ex.printStackTrace();
    }
    finally {
        //close connection to database
        closeconnection();
     }
 }
 

 public void view_Gallery(int gallery_num, JspWriter out) throws IOException{
    try{
        con= DriverManager.getConnection(url,id,pwd);
        Statement stmt = con.createStatement();
        String sql="SELECT * FROM gallery.image WHERE gallery_id='"+gallery_num+"';";
        ResultSet rs=stmt.executeQuery(sql);
        //prepare table and form FORM NAME : 
        out.println("<form NAME=\"imagetable\" method=\"POST\">");
        out.println("<Table>");
        out.println("Viewing Gallery #" + gallery_num + ".");
        out.println("<tr>");
        out.println("<td> Title </td>" + "<td> Image </td>" + "<td> Gallery ID </td>" + "<td> Artist ID </td>" + "<td> Detail ID </td>");
        while (rs.next()) {
            out.println("<tr>");
            out.println("<td>"+rs.getString("title")+ "<br><input type=\"radio\" name=\"imageselect\" value=\""+rs.getString("detail_id")+"\"" +"</td>");
            out.println("<td><img src = \"" + rs.getString("link")+ "\" alt=\"ERROR\"> </td>");
            out.println("<td>"+rs.getString("gallery_id")+"</td>");
            out.println("<td>"+rs.getString("artist_id")+"</td>");
            out.println("<td>"+rs.getString("detail_id")+"</td>");
            out.println("</tr>");
        }
        out.println("</Table>");
        out.println("<input type = \"submit\" value = \"View Image Details\"/>");
        out.println("</form>");
    }
    catch(SQLException ex){
        String message = "ERROR: " + ex.getMessage();
        out.println(message);
        ex.printStackTrace();
    }
    finally {
        //close connection to database
        closeconnection();
     }
 }
 

 public void closeconnection(){
    if (con != null) {
        // closes the database connection
        try {
            con.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
 }
 
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- HOMEWORK #2 -->\n");
      out.write("<!-- Gerry Su #16325043 -->\n");
      out.write("<!-- EECS 118 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	String funcID = request.getParameter("funcID");
	String name = request.getParameter("name");

      out.write("\n");
      out.write("<!-- LOADING THE DRIVER -->\n");

try {
    Class.forName("com.mysql.jdbc.Driver").newInstance();
    }
    catch(Exception e) {
    out.println("can't load mysql driver");
    out.println(e.toString());
}

      out.write("\n");
      out.write("<!-- TO CREATE A CONNECTION WITH MySQL SERVER FOR THE DATABASE \"gallery\" -->\n");
      out.write('\n');
      out.write("\n");
      out.write("<style>\n");
      out.write("table, th, td {\n");
      out.write("    border: 1px solid black;\n");
      out.write("    border-collapse: collapse;\n");
      out.write("}\n");
      out.write("th, td {\n");
      out.write("    padding: 15px;\n");
      out.write("    text-align: left;\n");
      out.write("}\n");
      out.write("p{\n");
      out.write("    padding-left:5em\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write(" <!-- TO PERFORM SQL QUERIES -->\n");
      out.write(" <!-- List all Galleries and Select gallery Function -->\n");
      out.write(" ");
      out.write('\n');
      out.write(' ');
      out.write('\n');
      out.write(' ');
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write(" <!-- Close connection function -->\n");
      out.write(" ");
      out.write("\n");
      out.write("\n");
      out.write(" <!-- To Add a Tuple into a Table -->\n");
      out.write(" <!-- ");
 /*
    PreparedStatement pstmt = con.prepareStatement("insert into customer values
    (default,?,?,?)",Statement.RETURN_GENERATED_KEYS);
    pstmt.clearParameters();
    pstmt.setString(1, name);
    pstmt.setString(2, street);
    pstmt.setString(3, city);
    pstmt.executeUpdate();
    rs=pstmt.getGeneratedKeys();
    while (rs.next()) {
    out.println("Successfully added. Customer_ID:"+rs.getInt(1));
    }*/
 
      out.write(" -->\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<h2><center> Web application with Database</center></h2>\n");
      out.write("<h3><center> MiniProject #2 by Gerry Su 16325043</center></h3>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write(" <!-- Reload Page button -->\n");
      out.write("<center>\n");
      out.write("<input type=\"button\" value=\"Refresh Page\" onClick=\"window.location.href=window.location.href\">\n");
      out.write("</center>\n");
      out.write("\n");
      out.write("\n");
      out.write(" <FORM NAME=\"form1\" METHOD=\"POST\">\n");
      out.write("     <INPUT TYPE=\"HIDDEN\" NAME=\"buttonName\">\n");
      out.write("     <INPUT TYPE=\"BUTTON\" VALUE=\"List all Galleries\" ONCLICK=\"list_Gallery()\">\n");
      out.write(" </FORM>\n");
      out.write("\n");
      out.write(" <SCRIPT LANGUAGE=\"JavaScript\">\n");
      out.write("     function list_Gallery()\n");
      out.write("     {\n");
      out.write("         document.form1.buttonName.value = \"List_gallery\";\n");
      out.write("         form1.submit();\n");
      out.write("     } \n");
      out.write(" </SCRIPT>\n");
      out.write("\n");
      out.write("<!-- List_Gallery Table will appear here -->\n");

String check = request.getParameter("buttonName");
if(check != null && check.equals("List_gallery")) {
       list_Gallery(out);
}

      out.write('\n');
      out.write('\n');

check = request.getParameter("galleryselect");
if(check != null) {
       out.println("You selected gallery #"+ check+".");
       //execute gallery function
       view_Gallery(Integer.valueOf(check), out);
}

      out.write("\n");
      out.write("\n");
      out.write("<h3>Add a Gallery</h3>\n");
      out.write("<form method=\"post\" action=\"querypage.jsp\">\n");
      out.write("<input type= \"hidden\" name =\"AddGallery\" value = \"\">\n");
      out.write("Gallery Name:<br>\n");
      out.write("<input type=\"text\" name=\"name\">\n");
      out.write("<br>\n");
      out.write("Description:<br>\n");
      out.write("<input type=\"text\" name=\"description\">\n");
      out.write("<input type=\"submit\" value=\"submit\">\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<h3>Add an Artist</h3>\n");
      out.write("<form method=\"post\" action=\"querypage.jsp\">\n");
      out.write("<input type= \"hidden\" name =\"AddArtist\" value = \"\">\n");
      out.write("Artist Name:<br>\n");
      out.write("<input type=\"text\" name=\"name\">\n");
      out.write("<br>\n");
      out.write("Birth Year:<br>\n");
      out.write("<input type=\"text\" name=\"year\">\n");
      out.write("<br>\n");
      out.write("Country:<br>\n");
      out.write("<input type=\"text\" name=\"country\">\n");
      out.write("<br>\n");
      out.write("Description:<br>\n");
      out.write("<input type=\"text\" name=\"description\">\n");
      out.write("<input type=\"submit\" value=\"submit\">\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<h3>Add an Image</h3>\n");
      out.write("<h4>Please fill in all the blanks</h4>\n");
      out.write("<form method=\"post\" action=\"querypage.jsp\">\n");
      out.write("<input type= \"hidden\" name =\"AddImage\" value = \"\">\n");
      out.write("Title:\n");
      out.write("<input type=\"text\" name=\"title\">\n");
      out.write("<br></td>\n");
      out.write("Link to Image (URL):&emsp;\n");
      out.write("<input type=\"text\" name=\"urlInput\" maxlength=\"200\">\n");
      out.write("<br>\n");
      out.write("Gallery ID:\n");
      out.write("<input type=\"text\" name=\"gallery_id\" style=\"width: 35px\">\n");
      out.write("<br>\n");
      out.write("Artist ID:\n");
      out.write("<input type=\"text\" name=\"artist_id\" style=\"width: 35px\">\n");
      out.write("<br>\n");
      out.write("Year:\n");
      out.write("<input type=\"text\" name=\"picture_year\" style=\"width: 50px\">\n");
      out.write("<br>\n");
      out.write("Type:\n");
      out.write("<input type=\"text\" name=\"picture_type\" style=\"width: 100px\">\n");
      out.write("<br>\n");
      out.write("Width:\n");
      out.write("<input type=\"text\" name=\"picture_width\" style=\"width: 75px\">\n");
      out.write("<br>\n");
      out.write("Height:\n");
      out.write("<input type=\"text\" name=\"picture_height\" style=\"width: 75px\">\n");
      out.write("<br>\n");
      out.write("Location:\n");
      out.write("<input type=\"text\" name=\"picture_location\">\n");
      out.write("<br>\n");
      out.write("Description:<br>\n");
      out.write("<textarea name=\"picture_description\" cols=\"30\" rows=\"6\" maxlength=\"45\"></textarea>\n");
      out.write("<input type=\"submit\" value=\"submit\">\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
