/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2018-10-16 05:18:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.io.*;
import java.sql.*;

public final class querypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("   <head>\n");
      out.write("      <title>Query Page</title>\n");
      out.write("   </head>\n");
      out.write("   \n");
      out.write("   <body>\n");
      out.write("    ");

    //Add gallery
    if(request.getParameter("AddGallery")!=null){
        String name=request.getParameter("name");
        String description=request.getParameter("description");
        Connection conn = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://127.0.0.1:3306/gallery";
            String id="gallery";
            String pwd="eecs118";
            conn = DriverManager.getConnection(url,id,pwd);
            Statement st=conn.createStatement();
            
            if(name.equals("")){
                out.println("Please enter a name.");
            }

            if(!name.equals("")){
                int i=st.executeUpdate("INSERT INTO gallery(name, description)values('"+name+"','"+description+"')");
                if (i>0){
                    out.println("Gallery is successfully inserted!");
                }
                else{
                    out.println("Gallery failed to insert! Try again?");
                }
            }
        }
        catch(Exception e){
            System.out.print(e);
            e.printStackTrace();
        }
        finally {
            if (conn != null) {
                // closes the database connection
                try {
                    conn.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }
    else if (request.getParameter("AddArtist")!=null){
        String name=request.getParameter("name");
        String year = request.getParameter("year");
        String country = request.getParameter("country");
        String description=request.getParameter("description");
        Connection conn = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://127.0.0.1:3306/gallery";
            String id="gallery";
            String pwd="eecs118";
            conn = DriverManager.getConnection(url,id,pwd);
            Statement st=conn.createStatement();
            
            if(name.equals("") || year.equals("") || country.equals("")){
                out.println("Please fill in name/year/country.");
            }
            else{
                int i=st.executeUpdate("INSERT INTO artist(name, birth_year, country, description)values('"+name+"','"+year+"','"+country+"','"+description+"')");
                if (i>0){
                    out.println("Artist is successfully inserted!");
                }
                else{
                    out.println("Artist failed to insert! Try again?");
                }
            }
        }
        catch(Exception e){
            System.out.print(e);
            e.printStackTrace();
        }
        finally {
            if (conn != null) {
                // closes the database connection
                try {
                    conn.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }
    else if (request.getParameter("AddImage")!=null){
        String title=request.getParameter("title");
        String urlInput = request.getParameter("urlInput");
        String gallery_id = request.getParameter("gallery_id");
        String artist_id=request.getParameter("artist_id");
        String picture_year = request.getParameter("picture_year");
        String picture_type = request.getParameter("picture_type");
        String picture_width = request.getParameter("picture_width");
        String picture_height = request.getParameter("picture_height");
        String picture_location = request.getParameter("picture_location");
        String picture_description = request.getParameter("picture_description");
        Connection conn = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://127.0.0.1:3306/gallery";
            String id="gallery";
            String pwd="eecs118";
            conn = DriverManager.getConnection(url,id,pwd);
            Statement st=conn.createStatement();
            
            if(title.equals("") || urlInput.equals("") || gallery_id.equals("") || artist_id.equals("")
            || picture_year.equals("") || picture_type.equals("") || picture_width.equals("") || picture_height.equals("")
            || picture_location.equals("") || picture_description.equals("")){
                out.println("Please fill in everything.");
            }
            else{
                int i=st.executeUpdate("INSERT INTO image(title, link, gallery_id, artist_id, detail_id)values('"+title+"','"+urlInput+"',"+gallery_id+","+artist_id+",'0')",st.RETURN_GENERATED_KEYS);
                if (i>0){
                    //create details then modify image
                    ResultSet rs = st.getGeneratedKeys();
                    rs.next();
                    int imageID = rs.getInt(1);
                    int j=st.executeUpdate("INSERT INTO detail(image_id, year, type, width, height, location, description)values('"+imageID+"','"+picture_year+"','"+picture_type+"','"+picture_width+"','"+picture_height+"','"+picture_location+"','"+picture_description+"')",st.RETURN_GENERATED_KEYS);
                    if(j>0){
                        rs = st.getGeneratedKeys();
                        rs.next();
                        int detailID = rs.getInt(1);
                        int k = st.executeUpdate("UPDATE `gallery`.`image` SET `detail_id` = '"+detailID+"' WHERE (`image_id` = '"+imageID+"');");
                        if(k>0){
                            out.println("Image is successfully inserted!");
                        }
                    }
                    else{
                        out.println("Image failed to insert! Detail failed to create. Try again?");
                    }
                }
                else{
                    out.println("Image failed to insert! Try again?");
                }
            }
        }
        catch(Exception e){
            System.out.print(e);
            e.printStackTrace();
        }
        finally {
            if (conn != null) {
                // closes the database connection
                try {
                    conn.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }
    
      out.write("\n");
      out.write("        <br>\n");
      out.write("\n");
      out.write("        <button onclick=\"goBack()\">Go Back</button>\n");
      out.write("        <script>\n");
      out.write("        function goBack(){\n");
      out.write("            window.history.back()\n");
      out.write("        }\n");
      out.write("        </script>\n");
      out.write("   </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
